---
output: 
  html_document: 
    keep_md: yes
---
# Project Details

* Name: Delaney Moran 
* Project title: Differential Distributions of Starbucks and Dunkin' Donuts in Eastern MA
* Abstract: 
The present analysis explores the comparative distributions of Dunkin’ Donuts and Starbucks in eastern Massachusetts. These two franchises are both highly successful coffeehouse chains despite a competitive market with low profit margins. Massachusetts was selected as the location of interested because it is my home state, and I know from experience there are strong loyalties by different groups of people to both Dunkin’ Donuts and Starbucks. Mapping both franchises revealed that there are many more Dunkin’ Donuts than Starbucks locations in eastern Massachusetts, and their densities differ by city vs. suburbs as well as by county. Additionally, the franchise density of Starbucks and Dunkin’ Donuts in a census tract are moderately associated with income. Overall, the present investigation reveals that Dunkin’ Donuts and Starbucks distributions differ both geographically, but also economically. Income and demographic data for this region was obtained from [Social Explorer](http://old.socialexplorer.com/pub/reportdata/HtmlResults.aspx?reportid=R11178485), and the MA shapefile was loaded [here](https://catalog.data.gov/dataset/tiger-line-shapefile-2015-state-massachusetts-current-census-tract-state-based-shapefile).

```{r, echo=FALSE, warning = FALSE}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggmap))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(rgdal))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(RCurl))
suppressPackageStartupMessages(library(maptools))
suppressPackageStartupMessages(library(rgeos))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(rvest))
suppressPackageStartupMessages(library(spatialEco))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(knitr))

Eastern <- c(5, 9, 17, 21, 23, 25)

#downloaded from social explorer ACS2014
MAincomedata <-read.csv("./data/MAincomedata.csv")

#filter to only tracts in counties in eastern MA and select relevant columns
MAincomedata <- MAincomedata %>%
  filter(Geo_STATE == 25) %>%
  filter(Geo_COUNTY %in% Eastern) %>%
  select(Geo_NAME, Geo_QName, Geo_STATE, Geo_COUNTY, Geo_FIPS, Geo_TRACT,
         SE_T001_001, SE_T002_002, SE_T057_001,
         SE_T056_001,
         SE_T056_002,
         SE_T056_003,
         SE_T056_004,
         SE_T056_005,
         SE_T056_006,
         SE_T056_007,
         SE_T056_008,
         SE_T056_009,
         SE_T056_010,
         SE_T056_011,
         SE_T056_012,
         SE_T056_013,
         SE_T056_014,
         SE_T056_015,
         SE_T056_016,
         SE_T056_017) %>%
  rename(total_population = SE_T001_001,
         pop_density = SE_T002_002,
         med_inc = SE_T057_001) %>%
  filter(!is.na(med_inc)) %>%
  mutate(Geo_FIPS = as.factor(Geo_FIPS)) %>%
  mutate(County = ifelse(Geo_COUNTY == 5, "Bristol",
                  ifelse(Geo_COUNTY == 9, "Essex",
                  ifelse(Geo_COUNTY == 17, "Middlesex",
                  ifelse(Geo_COUNTY == 21, "Norfolk",
                  ifelse(Geo_COUNTY == 23, "Plymouth",
                  ifelse(Geo_COUNTY == 25, "Suffolk", NA)))))))

#Load MA shapefiles
#https://catalog.data.gov/dataset/tiger-line-shapefile-2015-state-massachusetts-current-census-tract-state-based-shapefile
shapefile_path <- "./data/tl_2015_25_tract/"
map_obj <- readOGR(dsn = shapefile_path, layer = "tl_2015_25_tract")

# Convert Shapefile to ggplot Data Frame
map_obj$id <- rownames(map_obj@data)
map_points <- fortify(map_obj, region="id")
map_df <- inner_join(map_points, map_obj@data, by="id")

MAmap <- ggplot() +
  geom_polygon(aes(x = long, y = lat, group=group), data=map_df) +
  labs(x="Longitude", y="Latitude") +
  geom_path(size = 1.5) +
  coord_map()

map_census <- inner_join(map_df, MAincomedata, by = c("GEOID" = "Geo_FIPS"))

sbloc <- read.csv("./data/sbloc.csv")
ddloc <- read.csv("./data/ddloc.csv")

#SB locations
sb_coord <- sbloc %>%
  select(long, lat)
sb_data <- sbloc %>%
  select(place_id)
CRS <- "+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0 "
sbloc_sp <- SpatialPointsDataFrame(sb_coord, sb_data, proj4string = CRS(CRS))

map_with_sb <- point.in.poly(sbloc_sp, map_obj)
map_with_sb_id <- merge(sbloc_sp, map_with_sb, by = "place_id")
map_with_sb_id <- sp.na.omit(map_with_sb_id)


#DD locations
dd_coord <- ddloc %>%
  select(long, lat)
dd_data <- ddloc %>%
  select(place_id)
CRS <- "+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0 "
ddloc_sp <- SpatialPointsDataFrame(dd_coord, dd_data, proj4string = CRS(CRS))

map_with_dd <- point.in.poly(ddloc_sp, map_obj)
map_with_dd_id <- merge(ddloc_sp, map_with_dd, by = "place_id")
map_with_dd_id <- sp.na.omit(map_with_dd_id)


#Count DDs and SBs by census tract
DDlist <- as.data.frame(map_with_dd_id) %>%
  select(place_id, lat, long, GEOID) %>%
  rename(dd_place_id = place_id,
         dd_lat = lat,
         dd_long = long) %>%
  mutate(GEOID = as.factor(as.character(GEOID)))

SBlist <- as.data.frame(map_with_sb_id) %>%
  select(place_id, lat, long, GEOID) %>%
  rename(sb_place_id = place_id,
         sb_lat = lat,
         sb_long = long) %>%
  mutate(GEOID = as.factor(as.character(GEOID)))

tracts_w_dd <- as.data.frame(map_obj) %>%
  select(GEOID, NAMELSAD) %>%
  left_join(DDlist, by = "GEOID") %>%
  mutate(dd = ifelse(is.na(dd_place_id), 0, 1)) %>%
  group_by(GEOID) %>%
  summarise(numDD = sum(dd))

tracts_w_sb <- as.data.frame(map_obj) %>%
  select(GEOID, NAMELSAD) %>%
  left_join(SBlist, by = "GEOID") %>%
  mutate(sb = ifelse(is.na(sb_place_id), 0, 1)) %>%
  group_by(GEOID) %>%
  summarise(numSB = sum(sb))

tracts_w_SBDD <- left_join(tracts_w_dd, tracts_w_sb, by = "GEOID")

MAincomedata2 <- left_join(MAincomedata, tracts_w_SBDD, by = c ("Geo_FIPS" = "GEOID")) %>% 
    mutate(sb_1000 = numSB * 1000 / total_population,
         sb_1000 = ifelse(sb_1000 == Inf, NA, sb_1000),
         sb_1000 = ifelse(total_population < 1000, NA, sb_1000),
         dd_1000 = numDD * 1000 / total_population,
         dd_1000 = ifelse(dd_1000 == Inf, NA, dd_1000),
         dd_1000 = ifelse(total_population < 1000, NA, dd_1000))

totals <- MAincomedata2 %>%
  summarise(Starbucks_Count = sum(numSB),
            DunkinDonuts_Count = sum(numDD))

#Calculate franchises per 1000
#There is one census tract with a very small population (480), but 5 Dunkin' Donuts
#and 6 Starbucks...this seems like an anomaly. I am filtering out all tracts that
#have fewer than 1000 people in them
map_census2 <- left_join(map_census, tracts_w_SBDD, by = "GEOID") %>%
  mutate(sb_1000 = numSB * 1000 / total_population,
         sb_1000 = ifelse(sb_1000 == Inf, NA, sb_1000),
         sb_1000 = ifelse(total_population < 1000, NA, sb_1000),
         dd_1000 = numDD * 1000 / total_population,
         dd_1000 = ifelse(dd_1000 == Inf, NA, dd_1000),
         dd_1000 = ifelse(total_population < 1000, NA, dd_1000))


#Plot DD and SB locations!
MAmap +
  geom_point(data = ddloc,
             aes(x = long, y = lat),
             color = 'orange',
             size = 1.5) +
  geom_point(data = sbloc,
             aes(x = long, y = lat),
             color = 'green',
             size = 1.5) +
  coord_map() +
  theme_bw() +
  labs(title = "Locations of Starbucks and Dunkin' Donuts in Eastern MA")
```

